[workspace]
members = [
    "programs/airdrop0"
]
resolver = "2"

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1

[dependencies]
anchor-cli = "0.31.1"
solana-program = "2.1.22"
